#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFgO6oQLfKAPfvDXUbuakKv2l5P5uP5hIOH/ASd+4W4tTW6Lyhg4NqnUmg1/rVuvoo2cbhiRxTpM9/UV/mdjRUTaad0+x4KBKhp4Zj7FDBuC8yejKxMHyB/di3rZL6nNoFgCtulORZCseWKeRf0UILv6Y+TXGhatL7WV+IbctYtWBvASqNuofP5jeWg8RNCcemJQ4rH3LPt804jWVcV8Mt6A2nJyCMgGTe5yl8xQm+B4FRJ1Jo9gNKslacNFPQ6wud1zqoJALr6+ZESsgyOQF3JCafA8xjtlpp3Vv4jL25NytVqMTYWGCo2NpqK3JLSWnA3pi5Ezj2b1haDctd1jmb aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== teacher-key
disable_root: false 
package_update: true
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - mariadb-server
  - php-mysqli
  - adminer
write_files:
  - path: /var/www/html/index.php
    content: |
      <?php
      phpinfo();
      ?>
  - path: /etc/mysql/mariadb.conf.d/50-server.cnf
    content: |
      # MariaDB server configuration file.
      # You can copy the configuration here from the existing configuration and modify the bind address.
      [mysqld]
      bind-address = 0.0.0.0
runcmd:
  - apt update
  - apt install -y git
  - cd ~
  - git clone https://gitlab.com/ch-tbz-it/Stud/m346/m346scripts.git
  - cp ./m346scripts/KN03/*.php /var/www/html/
  - sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'Dominic' WITH GRANT OPTION;"
  - systemctl restart mariadb.service
  - systemctl restart apache2
  - a2enconf adminer
  - systemctl restart apache2
